drop table if exists BOOKINGS;
create table BOOKINGS(ID serial, FIRST_NAME varchar(5) NOT NULL);



DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS TRANSACTIONS;

CREATE TABLE ACCOUNTS ( 
ID BIGSERIAL NOT NULL AUTO_INCREMENT CONSTRAINT PK_ACCOUNTS PRIMARY KEY, 
BALANCE NUMBER (14,4) NOT NULL CHECK (BALANCE >= 0), 
CURRENCY CHAR (3) NOT NULL,
CREATED_AT DATE 
); 

CREATE TABLE TRANSACTIONS ( 
ID BIGSERIAL NOT NULL AUTO_INCREMENT CONSTRAINT PK_TRANSACTIONS PRIMARY KEY,  
SOURCE_ACCOUNT_ID NUMBER (11) NOT NULL REFERENCES ACCOUNTS(ID), 
TARGET_ACCOUNT_ID NUMBER (11) NOT NULL REFERENCES ACCOUNTS(ID), 
AMOUNT NUMBER (14,4),
CURRENCY CHAR (3) NOT NULL
); 
